### PR TITLE
Allow \Stringable in ID return type on ProcessedMessage

### PR DESCRIPTION
**Pull request by balazscsaba2006**

### CODE REVIEW

**Comment by kbond** [comment]
What about `string|int|\Stringable|null`? It needs to be scalar to access the details route.

**Comment by balazscsaba2006** [comment]
Yes, `\Stringable` would work just fine.

**Comment by balazscsaba2006** [comment]
@kbond I have added `\Stringable` to the return type.

**Review by kbond — APPROVED** [review]

**Comment by kbond** [comment]
Thanks @balazscsaba2006!

**Pull request merged**
