### PR TITLE
feat!: add wait/handle time to `ProcessedMessage`

### LINKED ISSUE #97: PostgreSQL averageWaitTime & averageHandlingTime are not working
We are using PostgreSQL and the averageWaitTime and averageHandlingTime always result to `0.0`.
(`$this->storage->averageWaitTime(new Specification())`)

As far as I can see the following query is executed (in case of `averageWaitTime`):
```
SELECT AVG(p0_.received_at - p0_.dispatched_at) AS sclr_0 FROM processed_message p0_ LIMIT 1;
```

Resulting into this:
```
array:1 [
  1 => "00:02:22.468872"
]
```

Inside the [ORMStorage.php#L98](https://github.com/zenstruck/messenger-monitor-bundle/blob/72568b7e2b98044f9f272f831fa32704752bdb31/src/History/Storage/ORMStorage.php#L98) its being casted to a `float` which is not working in this scenario because the string is not formatted as float.

Is this a known problem? I can create a pull request but I am curious how this should be fixed because I guess the problem doesn't exist in MySQL :)

### PR DESCRIPTION
**Pull request by kbond**
Fixes #97.

This is a BC break and will require existing apps to create a migration. The migration would need to either clear the existing `ProcessedMessage`'s or calculate the values when adding the fields.

This isn't ideal but feels like the best way to eliminate the timestamp diff db logic that DB platforms all handle differently.

TODO:
- [x] `UPGRADE.md`

### CODE REVIEW

**Comment by kbond** [comment]
💪🏻 Ok, `averageWaitTime` & `averageHandlingTime` work consistently across sqlite/mysql/postgres.

I think this is the best way to handle but @Chris53897, @SherinBloemendaal, @bobvandevijver, any thoughts?

**Comment by bobvandevijver** [comment]
LGTM 👍🏻

**Comment by bendavies** [comment]
@kbond how about storing micro seconds for sub second precision?
many of my messages show 0 seconds for handled time, it would be great to see milliseconds!!
maybe squeeze in before the 0.5 release?

**Comment by kbond** [comment]
I was thinking about this.

My only concern is timestamp fields don't store partial seconds (IIRC). Maybe not an issue but the timestamps and wait/handle time's won't match up.

Thinking to store as `seconds * 1000` instead of a decimal field to avoid any inconsistencies between db platform (not sure if there are any).

Need to make this decision before 0.5.0 to avoid a BC break for existing data...

**Comment by bendavies** [comment]
here i used `decimal(16,6)` with `DateTimeImmutable->format('U.u')` and it seemed fine on postgres and mysql
https://github.com/SymfonyCasts/messenger-monitor-bundle/pull/43

**Comment by kbond** [comment]
Ok cool, I have tests for different db platforms now so let's see!

**Comment by kbond** [comment]
Why did you use decimal instead of float for the type? From what I'm seeing, a float would require less bytes than a 16,6 decimal.

**Comment by bendavies** [comment]
floats didn't work on mariadb

https://github.com/SymfonyCasts/messenger-monitor-bundle/pull/43#issuecomment-1263279207
https://github.com/SymfonyCasts/messenger-monitor-bundle/pull/43#issuecomment-1269975615

[SymfonyCasts/messenger-monitor-bundle@`1fed242` (#43)](https://github.com/SymfonyCasts/messenger-monitor-bundle/pull/43/commits/1fed24236471fad32b48bc8c4ded68a88130889e)

**Comment by kbond** [comment]
Ok, good to know! Decimal it is

**Comment by bendavies** [comment]
i'm actually not sure if my comment back then was a typo and i meant postgres.
but compare these on postgres and you'll see floats suffer from the same problem as php with floats.
```sql
SELECT avg(n) FROM unnest('{0.1,0.2}'::float[]) n; # 0.15000000000000002
SELECT avg(n) FROM unnest('{0.1,0.2}'::decimal[]) n; # 0.15000000000000000000
```

**Comment by kbond** [comment]
I watched this also: https://planetscale.com/learn/courses/mysql-for-developers/schema/decimals

Which talks about the same thing but... For milli or even micro seconds, this approximation would be fine, no?

**Comment by bendavies** [comment]
sure it'll use more bytes for storage, but is that a concern given the other columns on this table which are far larger?
that said, this does seem a valid occasion where an approximation might be seemed good enough.

**Comment by bobvandevijver** [comment]
Why not just store the milliseconds (or even micro) in the int field? I very much doubt that (assuming 64 bit signed, bigint in mariadb and postgres) wait time and handle time would ever by larger than 2.56*10^9 hours.

Unsigned ints are not supported on postgres, so that is not an option.

Personally I always try to stay away from floats whenever possible.

**Comment by kbond** [comment]
Ok, I was also thinking storing the milliseconds. I think I'll do that. I doubt there's a need for knowing down to the microsecond.

**Pull request merged**
