### PR TITLE
Add support for multiple messages per task introduced in Scheduler 6.4

### PR DESCRIPTION
**Pull request by dontfreakout**
This commit adds compatibility with symfony/scheduler > 6.4 and maintains backward compatibility with scheduler 6.3. The changes allow handling multiple messages per task in TaskInfo.php, and reflect these changes in the displaying of messages in schedule.html.twig and dispatching messages in MessengerMonitorController.php.

### CODE REVIEW

**Comment by kbond** [comment]
Thanks @dontfreakout, sorry for the delay reviewing this. Could you resolve the conflict?

Also, why don't we bump min deps to 6.4, 6.3 is EOL.

**Review by kbond — APPROVED** [review]
Let me know when it's ready to merge @dontfreakout.

**Comment by dontfreakout** [comment]
Hello @kbond 
I resolved conflicts and bumped min deps to 6.4, also removed 6.3 from ci tests :wink:

**Comment by kbond** [comment]
Thanks @dontfreakout!

**Pull request merged**
